clc;
clear all;
t0=0;
tk=100;
hi=0.01;
Imax=10;
C=1;
Ena=115;
Ek=-12;
El=10.6;
gNa=120;
gK=36;
gL=0.3;
u0=0;

[tout,mout,nout,hout,uout,Inaout,Ikout,Ilout] = hodgkin_huxley( t0,tk,hi,Imax,C,Ena,Ek,El,gNa,gK,gL,u0 );

figure;
plot(tout,mout);
title('Parametry m,n,h w zaleznosci od czasu');
hold on;
plot(tout,nout);
plot(tout,hout);
hold off;xlim([0 100]);
ylabel('U [mV]');
xlabel('czas [ms]');
legend('m','n','h');

figure;
plot(tout,Inaout);
hold on;
plot(tout,Ikout);
plot(tout,Ilout);
hold off;xlim([0 100]);
title('Natezenia w zaleznosci od czasu');
xlabel('czas [ms]');
ylabel('I [mA]');
legend('I_N_a','I_K','I_L');

C=0.8;
Ena=100;
Ek=-12;
El=4;
gNa=120;
gK=26;
gL=0.13;
[tout,mout,nout,hout,uout,Inaout,Ikout,Ilout] = hodgkin_huxley( t0,tk,hi,Imax,C,Ena,Ek,El,gNa,gK,gL,u0 );

figure;
plot(tout,mout);
title('Parametry m,n,h w zaleznosci od czasu dla najnizszych parametrow');
hold on;
plot(tout,nout);
plot(tout,hout);
hold off;xlim([0 100]);
ylabel('U [mV]');
xlabel('czas [ms]');
legend('m','n','h');

figure;
plot(tout,Inaout);
hold on;
plot(tout,Ikout);
plot(tout,Ilout);
hold off;xlim([0 100]);
title('Natezenia w zaleznosci od czasu dla najnizszych paramertow');
xlabel('czas [ms]');
ylabel('I [mA]');
legend('I_N_a','I_K','I_L');

C=1.5;
Ena=119;
Ek=-4;
El=22;
gNa=260;
gK=40;
gL=0.5;
[tout,mout,nout,hout,uout,Inaout,Ikout,Ilout] = hodgkin_huxley( t0,tk,hi,Imax,C,Ena,Ek,El,gNa,gK,gL,u0 );
figure;
plot(tout,mout);
title('Parametry m,n,h w zaleznosci od czasu dla najwyzszych parametrow');
hold on;
plot(tout,nout);
plot(tout,hout);
hold off;xlim([0 100]);
ylabel('U [mV]');
xlabel('czas [ms]');
legend('m','n','h');

figure;
plot(tout,Inaout);
hold on;
plot(tout,Ikout);
plot(tout,Ilout);
hold off;xlim([0 100]);
title('Natezenia w zaleznosci od czasu dla najwyzszych paramertow');
xlabel('czas [ms]');
ylabel('I [mA]');
legend('I_N_a','I_K','I_L');